### ISSUE TITLE
Update to FE12 patch?

### ISSUE THREAD

**Issue by silverjojo08** [R-YaTian/DSiEnhanced_Translation_Revision#1]
I understand if it's just not feasible or if you don't have interest in this, but would it be possible to update the FE12 patch to the most recent version available: https://forums.serenesforest.net/index.php?/topic/69176-updated-fe12-translation-patch-beta-2-released/

**Comment by R-YaTian** [comment]
> I understand if it's just not feasible or if you don't have interest in this, but would it be possible to update the FE12 patch to the most recent version available: https://forums.serenesforest.net/index.php?/topic/69176-updated-fe12-translation-patch-beta-2-released/

I cannot download this patch. Could you please send it to me?

**Comment by silverjojo08** [comment]
Oops, sorry about that. Here's another link for it: https://www.romhacking.net/translations/5622/

**Comment by R-YaTian** [comment]
> Oops, sorry about that. Here's another link for it: https://www.romhacking.net/translations/5622/

Oh. I have ever try this patch, but I found some "dsi-only" strings are missing. So I haven't use this patch finally. Now I found a way to restore these strings after do some research. I will upload a brand new patch in the near future.

**Comment by R-YaTian** [comment]
[FE12 English V3.01-B2 Patch](https://github.com/R-YaTian/DSiEnhanced_Translation_Revision/tree/main/FE12/English_ALT) is out!
